<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('user', array('action' => 'add')));

// Get the form label plugin
$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));
?>
<div class="form-group">
<?php
    $username = $form->get('username');
    echo $formLabel->openTag() . $username->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($username);
    echo $this->formElementErrors($username);
?>
</div>
<div class="form-group">
<?php
    $password = $form->get('password');
    echo $formLabel->openTag() . $password->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($password);
    echo $this->formElementErrors($password);
?>
</div>
<div class="form-group">
<?php
    $nome = $form->get('nome');
    echo $formLabel->openTag() . $nome->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($nome);
    echo $this->formElementErrors($nome);
?>
</div>
<div class="form-group">
<?php
    $email = $form->get('email');
    echo $formLabel->openTag() . $email->getOption('label') . $formLabel->closeTag();
    echo $this->formInput($email);
    echo $this->formElementErrors($email);
?>
</div>
<?php
$submit = $form->get('submit');
echo $this->formInput($submit);

echo $this->form()->closeTag($form) . PHP_EOL;
