<?php
$title = 'Adicionar um usuário';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('id')) . PHP_EOL;
echo $this->formRow($form->get('username')) . PHP_EOL;
echo $this->formRow($form->get('password')) . PHP_EOL;
echo $this->formRow($form->get('nome')) . PHP_EOL;
echo $this->formRow($form->get('email')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;