<div class="page-header">
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>
</div>

<p>Tem certeza que deseja deletar o usuário '<?php echo $this->escapeHtml($user->nome); ?>' ?</p>

<?php $url = $this->url('user', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo (int) $user->id; ?>" />
  <input class="btn btn-default" type="submit" name="del" value="Cancelar" />
  <input class="btn btn-success" type="submit" name="del" value="Confirmar" />
</div>
</form>