<div class="page-header">
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>
</div>
<div class="row">
    <div class="col-md-6">
        <a class="btn btn-primary" href="<?php echo $this->urlAdd; ?>">
            <span class="glyphicon glyphicon-user"></span> Adicionar um usuário
        </a>
    </div>
    <div class="col-md-6">
    <?php $form = $this->form; $search = $form->get('search') ?>
        <form class="navbar-form navbar-left pull-right" role="search">
        <div class="form-group">
            <?php echo $this->formInput($search); ?>
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
        </form>
    </div>
</div>
<p>
</p>
<div class="table-responsive">
    <table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Usuário</th>
        <th>Nome</th>
        <th>E-mail</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->paginator as $user): ?>
    <tr>
        <td><?php echo $user->id; ?></td>
        <td><?php echo $this->escapeHtml($user->username); ?></td>
        <td><?php echo $this->escapeHtml($user->nome); ?></td>
        <td><?php echo $this->escapeHtml($user->email); ?></td>
        <td>
            <div class="btn-group">
                <a class="btn btn-default btn-xs" title="Editar" href="<?php echo $this->placeholder('url')->edit .'/'. $user->id; ?>">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <!--
                    data-toggle="modal"
                    data-target=".bs-example-modal-sm"
                -->        
                <a
                    class="btn btn-default btn-xs mySmallModalLabel delete"
                    data-toggle="confirmDelete"
                    data-target="#confirmDelete"
                    data-user="<?php echo $this->escapeHtml($user->username); ?>"
                    title="Remover"
                    href="<?php echo $this->placeholder('url')->delete .'/'. $user->id; ?>"
                    >
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </div>
        </td>
    </tr>
    <?php endforeach; ?>
    <?php //echo $this->partialLoop('users.phtml', $this->paginator); ?>
    </table>
</div>

<div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination', array('route' => 'user')); ?>
</div>

<!-- Questiona exclusão de um usuário -->
<div id="confirmDelete" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"><?php echo $this->escapeHtml($this->title); ?></h4>
        </div>
        <div class="modal-body">
            <p>Deseja remover o usuário <span id="user"></span>?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button type="button" class="btn btn-success">Remover</button>
        </div>
    </div>
  </div>
</div>

<script type="text/javascript">
/*
(function ($) {
    $('.delete').on('click', function(e){
        e.preventDefault();
        $('#user').html($(this).attr('data-user'));
        $('#confirmDelete').modal('toggle');

        $('#confirmDelete .btn-success').on('click', function(e){
            alert('success');
        });
    });

    //$.extend(window, SlickEditor);

})(jQuery);
*/
</script>