<div class="page-header">
    <h1><?php echo $this->escapeHtml($this->title); ?></h1>
</div>
<p>
    <a class="btn btn-primary" href="<?php echo $this->urlAdd; ?>">
        <span class="glyphicon glyphicon-user"></span> Adicionar um usuário
    </a>
</p>
<?php echo $this->partial('messages.phtml'); ?>
<table class="table table-hover">
<tr>
    <th>Usuário</th>
    <th>Nome</th>
    <th>E-mail</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($this->paginator as $user): ?>
<tr>
    <td><?php echo $this->escapeHtml($user->username); ?></td>
    <td><?php echo $this->escapeHtml($user->nome); ?></td>
    <td><?php echo $this->escapeHtml($user->email); ?></td>
    <td>
        <a class="btn btn-primary btn-xs" title="Editar" href="<?php echo $this->placeholder('url')->edit .'/'. $user->id; ?>">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <a class="btn btn-danger btn-xs" title="Remover" href="<?php echo $this->placeholder('url')->delete .'/'. $user->id; ?>">
            <span class="glyphicon glyphicon-trash"></span>
        </a>
    </td>
</tr>
<?php endforeach; ?>
<?php //echo $this->partialLoop('users.phtml', $this->paginator); ?>
</table>

<div>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination', array('route' => 'user')); ?>
</div>