<?php 
$title = 'Usuários';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('user', array( 
        'action'=>'add'));?>">Adicionar um usuário</a></p>

<table class="table">
<tr>
    <th>Usuário</th>
    <th>Nome</th>
    <th>E-mail</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($users as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->username);?></td>
    <td><?php echo $this->escapeHtml($user->nome);?></td>
    <td><?php echo $this->escapeHtml($user->email);?></td>
    <td>
        <a href="<?php echo $this->url('user',
            array('action'=>'edit', 'id' => $user->id));?>">Editar</a>
        <a href="<?php echo $this->url('user',
            array('action'=>'delete', 'id' => $user->id));?>">Deletar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>