<tr>
    <td><?php echo $this->escapeHtml($this->user->username);?></td>
    <td><?php echo $this->escapeHtml($this->user->nome);?></td>
    <td><?php echo $this->escapeHtml($this->user->email);?></td>
    <td>
        <a href="<?php echo $this->placeholder('url')->edit .'/'. $this->user->id; ?>">Editar</a>
        <a href="<?php echo $this->placeholder('url')->edit .'/'. $this->user->id; ?>">Deletar</a>
    </td>
</tr>
